In [ ]:
import numpy as np

In [ ]:
array = np.array([[1,2,3,4,5],[6,7,8,9,0]])

In [ ]:
print (array)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [ ]:
array

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [ ]:
array.T

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9],
       [5, 0]])